### ISSUE TITLE
Latest nuget package is built in debug mode

### ISSUE THREAD

**Issue by jnyrup** [sestoft/C5#136]
## Description
I noticed that the published 3.0.0-rc is built in debug mode.
I'm not sure whether this is intentionally, but it was a surprise to me that it wasn't built in release mode.

https://nuget.info/packages/C5/3.0.0-rc
![image](https://github.com/sestoft/C5/assets/919634/ef7c85a1-a1af-4fc7-a87a-00d3bb2f6471)

## Solution
Build packages in release mode.

**Comment by ondfisk** [comment]
Not intentional. Fixed in 3.0.0 release.
