### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by bill-poole** [sestoft/C5#140]
There doesn't seem to have been any activity on this project for a very long time. There are two high severity security vulnerabilities in the current GA package's dependencies and the v3 RC version seems to be compiled in debug mode. We are in dire need of a new GA release. I would very much like to know whether this project is still being maintained before taking on a dependency to it.

Thanks in advance!

**Comment by ondfisk** [comment]
[C5 3.0.0](https://www.nuget.org/packages/C5/3.0.0) released - @bill-poole hope this works.

**Comment by ondfisk** [comment]
Also, we have been looking for (co)maintainers for a while, but not takers so far.
