### ISSUE TITLE
HashedLinkedList raises assertion error when adding lots of elements

### ISSUE THREAD

**Issue by ovidiomanteiga** [sestoft/C5#17]
C5 HashedLinkedList raises an assertion error at the method **splittaggroup** when adding lots of elements. In the attached image example, the list had close to 4 million integers.

As the debugger shows, previous-taggroup-tag (ptgt) is equal to _int.MaxValue - 1_ and next-taggroup-tag (ntgt) is equal to [int.MaxValue](http://msdn.microsoft.com/es-es/library/system.int32.maxvalue.aspx). So those values do not verify the assertion that `ptgt + 1 <= ntgt - 1`.

"[The C5 Generic Collection Library for C# and CLI](http://www.itu.dk/research/c5/latest/ITU-TR-2006-76.pdf)" technical report states at section 13.8 _Implementation of hashed linked lists_:

> Note, however, that the typical case of always inserting at the end of the list seems to be close to the worst-case scenario for maintaining the tags.

That is the case.

You can run this simple program that tries to reproduce this error: https://github.com/ovidiomanteiga/C5HashedLinkedListAssertionError

![c5hashedlinkedlistassertionerror](https://f.cloud.github.com/assets/5225102/1154219/e2f0b678-1f3a-11e3-93b3-305f29812237.png)

**Comment by ondfisk** [comment]
Issue fixed in version 3.0
