### ISSUE TITLE
Error when installing NuGet package in a portable .NET 4.5 project

### ISSUE THREAD

**Issue by azzlack** [sestoft/C5#23]
I get the following message when trying to install your package in a portable project targeting .NET 4.5.

AFAIK the fix is to create a new folder in your nuget lib folder named `portable-net45+win+wpa81+wp80` and drop the `C5.dll` in it before publishing it again.

```
Installing 'C5 2.3.0.1'.
Successfully installed 'C5 2.3.0.1'.
Adding 'C5 2.3.0.1' to Provision.Core.
Uninstalling 'C5 2.3.0.1'.
Successfully uninstalled 'C5 2.3.0.1'.
Install failed. Rolling back...
Could not install package 'C5 2.3.0.1'. 
You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80', 
but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.
```

**Comment by AArnott** [comment]
+1
It seems the source code is properly built to support wpa81, but the latest published nuget package doesn't reflect this.

**Comment by ondfisk** [comment]
Could you test it again

**Comment by AArnott** [comment]
It works for me now. Thanks.
