### ISSUE TITLE
Build proper documentation

### ISSUE THREAD

**Issue by Rhywden** [sestoft/C5#28]
I'm a bit annoyed currently because this page tells me to "use Sandcastle to build the documentation".

Nice sentiment when information on how to actually use that is a bit sparse. Not to mention that using the included Sandcastle project file results in this:

     SHFB: Warning BE0006: Unable to locate any documentation sources for 'C:\Users\xxxx\C5-master\C5\bin\Release\C5.dll' (Configuration: Debug Platform: AnyCPU)

**Comment by tommyettinger** [comment]
I just built some with SharpDox (I actually altered the source slightly of SharpDox so it would document some things correctly). I'm hosting the documentation on Github Pages for now. http://tommyettinger.github.io/home/C5/

**Comment by ondfisk** [comment]
Sandcastle has now been replaced by doxygen and documentation is available online at https://c5docs.azurewebsites.net/.
