### ISSUE TITLE
Clarify licence

### ISSUE THREAD

**Issue by hickford** [sestoft/C5#33]
Hi. Could you clarify (in the readme, and the Nuget page) exactly what the "BSD-style license" is? This might sound pernickety, but it's helpful to using the library at companies that are particular about open source (we have a set list of licences).

https://www.nuget.org/packages/C5

**Comment by hickford** [comment]
It looks to be exactly the MIT licence http://opensource.org/licenses/MIT

**Comment by ondfisk** [comment]
Yep it's the MIT license. I've updated the documentation to reflect that.
