### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by tkirill** [sestoft/C5#36]
Hi!

Can't find anything about thread safety in the documentation.  Are all collections thread safe or not?  Especially I'm interested in `IntervalHeap`.

**Comment by sestoft** [comment]
On 12Oct15 9:17, "Kirill Teplinskiy" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can't find anything about thread safety in documentation. Are all collections thread safe or not? Especially I'm interesting in IntervalHeap.

No part of C5 is designed to be thread safe. Search for "synchronized" in the C5 book.

It is commonly recognized that it is useless to make individual collection classes thread-safe unless they are also implemented in a manner that scales well with increased concurrency (such as .NET ConcurrentDictionary or Java's ConcurrentHashMap).

Instead, add you own locking, or confine access to one thread.

We have started working on thread-safe and scalable C5 collections, but this will take some time.

Peter

**Comment by tkirill** [comment]
@sestoft Thanks for clarification!
