### ISSUE TITLE
The covariant type parameter `T' must be invariantly valid

### ISSUE THREAD

**Issue by ramadansoft** [sestoft/C5#38]
Hi,

I am trying to use your library in my unity game.
I copied the CS folder in my project, and it seems to be working well, but I get this two compilation errors.

Assets/C5/IReadOnlyCollection.cs(8,22): error CS1961: The covariant type parameter `T' must be invariantly valid on `System.Collections.Generic.IReadOnlyCollection<T>'

Assets/C5/IReadOnlyList.cs(8,22): error CS1961: The covariant type parameter `T' must be invariantly valid on `System.Collections.Generic.IReadOnlyList<T>'

Thanks for advance.

**Comment by ondfisk** [comment]
You should reference the whole library using NuGet: Install-Package C5

**Comment by ramadansoft** [comment]
Thank you!
