### ISSUE TITLE
Solution doesn't compile

### ISSUE THREAD

**Issue by lundmikkel** [sestoft/C5#39]
Check the comments [here](https://github.com/sestoft/C5/commit/a852e7050983f5f086261382deb2a9edb22ebfc9#diff-3) and [here](https://github.com/sestoft/C5/commit/46be070318c786b761ee9b93cac6b1fe1fed3b56#diff-0).

**Comment by ondfisk** [comment]
Can you check the latest commit?

**Comment by lundmikkel** [comment]
It seems to work again. Thanks :+1:
