### ISSUE TITLE
Nuget NetStandard/Core Update

### ISSUE THREAD

**Issue by w9n** [sestoft/C5#55]
Hi,

Can you please update the Nuget?

**Comment by llint** [comment]
Backing this up +1

**Comment by llint** [comment]
When will the dotnet core / standard version be released? It seems I'll be desperately hoping to use C5 for my dotnet core based project. Thanks in advance!

**Comment by karldodd** [comment]
+1

**Comment by AArnott** [comment]
I'm working on this right now. Nearly done. I've done similar conversions dozens of times. I'll send a PR within a day or two.
