### ISSUE TITLE
Doesn´t work on Visual Studio 2015

### ISSUE THREAD

**Issue by abel406** [sestoft/C5#62]
Hi guys. After downloading the code, i tried to open the solution in VS 2015 but no project was loaded.Is there a brach that can be open with that version of microsoft VS ? Thanks.

**Comment by ondfisk** [comment]
Hi Abel
The latest bits require VS 2017 to compile as it's using latest .NET Standard 2.0 features.
There's no VS 2015 branch, sorry.

**Comment by abel406** [comment]
Thank you for the quick answer. I have to give it a try to .Net Standard 2.0.
