### ISSUE TITLE
Error at building project C5 in Visual Studio 2017 15.1 26403.0 Enterprise

### ISSUE THREAD

**Issue by abel406** [sestoft/C5#63]
I get this error message after an attempt to build the library:

> Error		Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='portable-net40+sl50+win8+wpa81+wp8'. They must be specified explicitly.	C5	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	84	

Please, any tip to build the library ?

Thanks.

**Comment by ondfisk** [comment]
I just cloned the repository and opened in VS 2017 (15.3.3).
I get the same error, but it automatically goes away after half a minute - when NuGet package restore has completed.
Do you still see the error?
