### ISSUE TITLE
State of project?

### ISSUE THREAD

**Issue by mikernet** [sestoft/C5#64]
What is the state of this project?

The #warning tags included by the devs in the source code indicating incorrect behavior and suspicions isn't particularly confidence inspiring given there haven't been any updates in a long time.

**Comment by mikernet** [comment]
Also this is what it says for the documentation for TreeBag<T>.UpdateOrAdd:

NOTE: the bag implementation is currently wrong! ?????

What's going on here? lol

**Comment by mikernet** [comment]
I noticed there is some code as well in the user guide that supposedly throws exceptions for the treebag. 
@sestoft  Can you please let me know if the treebag is indeed broken, as the biggest reason I wanted to use this library was for a index-accessible bag with O(log n) insert and retrieval time so this might be a bit of a bummer. I may be able to use a TreeSet instead - are there any known issues with that class?

**Comment by sestoft** [comment]
In what sense should TreeBag be "broken"?

On 15Nov17, 21:34, "Mike Marynowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed there is some code as well in the user guide that supposedly throws exceptions for the treebag.
@sestoft<https://github.com/sestoft> Can you please let me know if the treebag is indeed broken, as the biggest reason I wanted to use this library was for a index-accessible bag with O(log n) insert and retrieval time so this might be a bit of a bummer. I may be able to use a TreeSet instead - are there any known issues with that class?

**Comment by mikernet** [comment]
From your user guide examples: https://github.com/sestoft/C5/blob/master/C5.UserGuideExamples/TreebagBug20091113.cs

**Comment by mikernet** [comment]
Also line 1338 in redblacktreebag.cs starts like this:

```
#warning for bag implementation: count is wrong
                if (ActiveEvents != 0)
                    raiseForUpdate(item, olditem, 1);
                return true;
```
Not entirely sure what to make of that

**Comment by sestoft** [comment]
This was fixed on 2010-12-17.

On 15Nov17, 21:37, "Mike Marynowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


From your user guide examples: https://github.com/sestoft/C5/blob/master/C5.UserGuideExamples/TreebagBug20091113.cs

**Comment by sestoft** [comment]
If you do not use the events raised by updates to the collection you need not worry.

On 15Nov17, 21:40, "Mike Marynowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Also line 1338 in redblacktreebag.cs starts like this:

#warning for bag implementation: count is wrong
                if (ActiveEvents != 0)
                    raiseForUpdate(item, olditem, 1);
                return true;


Not entirely sure what to make of that

**Comment by mikernet** [comment]
I definitely will be, the events are the real selling point for this library as I need to track a diff of the collections as they change so I can push only the changes to a database.

**Comment by sestoft** [comment]
Oh! In this case the multiplicity will be wrong (always 1) in the ItemCountEventArgs<T> value passed to the ItemsRemoved and ItemsAdded events after an update.

This value is described like this on p 136 of the 2008 manual: "Read-only field int Count is the multiplicity with which the insertion or deletion occurred."

Sorry about that.

On 15Nov17, 21:47, "Mike Marynowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


I definitely will be, the events are the real selling point for this library as I need to track a diff of the collections as they change so I can push only the changes to a database.

**Comment by mikernet** [comment]
Okay thank you very much.
