### ISSUE TITLE
Time complexity of SortedArray<t> indexing

### ISSUE THREAD

**Issue by mikernet** [sestoft/C5#65]
Reading through the documentation and O(log n) performance for doing `this[i]` on a sorted array doesn't seem right. Shouldn't indexed access to an array be O(1)?

**Comment by sestoft** [comment]
Indeed this should be O(1).

Peter

On 10Nov17, 21:37, "Mike Marynowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Reading through the documentation and O(log n) performance for doing this[i] on a sorted array doesn't seem right. Shouldn't indexed access to an array be O(1)?
