### ISSUE TITLE
Single writer multiple readers pattern with snapshots

### ISSUE THREAD

**Issue by Kikimora** [sestoft/C5#66]
Hi,

I went over relevant sections in the doc but still a bit confused about this. Can I have one (and only one) thread updating tree while multiple other threads reading it snapshot?

Thanks

**Comment by sestoft** [comment]
It sounds like you are thinking of a multithreaded scenario, but the C5 collection classes are not threadsafe.

Peter

Sent from my iPad

On 12 Dec 2017, at 03.15, Andrey Verbin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I went over relevant sections in the doc but still a bit confused about this. Can I have one (and only one) thread updating tree while multiple other threads reading it snapshot?

Thanks

**Comment by Kikimora** [comment]
I see. I’ll probably roll my own implementation taking ideas from C5. 

Thanks

> 12 дек. 2017 г., в 10:20, Peter Sestoft <notifications@github.com> написал(а):
> 
> It sounds like you are thinking of a multithreaded scenario, but the C5 collection classes are not threadsafe. 
> 
> Peter 
> 
> Sent from my iPad 
>
