### ISSUE TITLE
Inconsistent default constructors

### ISSUE THREAD

**Issue by FruitcakeElemental** [sestoft/C5#67]
Hi Guys,

I've noticed a few collections are inconsistent whether they define a default constructor or not, this can have implications for things like the new() generic constraint.

I've created a patch that adds a default constructor to the ones that I found were missing, diff attached.

[default_constructor.diff.txt]
(https://github.com/sestoft/C5/files/1680304/default_constructor.diff.txt)
[default_constructor.diff.txt]

**Comment by ondfisk** [comment]
Please submit as a pull request and we'll have a look at it.

**Comment by FruitcakeElemental** [comment]
Can do, do i need permissions added to the project? its telling me i can't push to the repo.

Its my first open source contribution so i might be missing some knowledge.

**Comment by ondfisk** [comment]
No permissions needed.
You fork the repo and create a pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by FruitcakeElemental** [comment]
Created pull request: https://github.com/sestoft/C5/pull/68

**Comment by ondfisk** [comment]
Issue should be fixed in latest beta
