### ISSUE TITLE
compatibility with Unity

### ISSUE THREAD

**Issue by christougher** [sestoft/C5#91]
## Description
When Importing C5 into Unity 2019.3 a whole slew of errors occur.  I've seen references that c5 is/was actually compatible with Unity and I even have access to an older c5.dll that works, but was hoping to get this into Unity 

## Solution
Version of c5 that is able to be integrated into Unity

**Comment by ondfisk** [comment]
Can you provide some more context. Are you using the latest 3.0-beta?
No one on the team has any skills in Unity. Can you share a sample project which shows the issue?

**Comment by christougher** [comment]
actually I used an older version and it works fine.  Thanks.  I believe it stopped being compatible in February when:
* Retarget to .NET Standard 2.0 only

**Comment by ondfisk** [comment]
According to this: https://docs.microsoft.com/en-us/dotnet/standard/net-standard, Unity should be fine with .NET Standard 2.0.

**Comment by Ryan-M3** [comment]
I can confirm that C5 throws "999+" errors, at that changing to a commit vaguely around February fixes it. To reproduce: download Unity; start a new project; clone C5 into Assets folder; wait for Unity to automatically compile; check in-engine console for errors. I'm not proficient enough in C# to comment on the why.

**Comment by ondfisk** [comment]
@Ryan-M3 dumping the .cs files directly in Unity will not work as C5 compiles using C# 8.0.
It is targetting .NET Standard 2.0 which Unity supports.
Can you get the NuGet package instead?
I read somewhere that you could use https://github.com/GlitchEnzo/NuGetForUnity and then use https://www.nuget.org/packages/C5/3.0.0-beta

**Comment by Ryan-M3** [comment]
> 
> 
> @Ryan-M3 dumping the .cs files directly in Unity will not work as C5 compiles using C# 8.0.
> It is targetting .NET Standard 2.0 which Unity supports.
> Can you get the NuGet package instead?
> I read somewhere that you could use https://github.com/GlitchEnzo/NuGetForUnity and then use https://www.nuget.org/packages/C5/3.0.0-beta

Worked like a charm. The only gotcha was that I had to make sure I clicked "include pre-release" in order to get the exact version you specified. Using an older version led me to waste a little time troubleshooting my own error. :)

**Comment by ondfisk** [comment]
Great.
Will close the issue then.
We will hopefully be able to release a 3.0 version without pre very soon.
